// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	model "github.com/smeruelo/glow/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// CreateProject provides a mock function with given fields: project
func (_m *Store) CreateProject(project model.Project) error {
	ret := _m.Called(project)

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Project) error); ok {
		r0 = rf(project)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProject provides a mock function with given fields: id, userID
func (_m *Store) DeleteProject(id string, userID string) error {
	ret := _m.Called(id, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetProject provides a mock function with given fields: id
func (_m *Store) GetProject(id string) (model.Project, error) {
	ret := _m.Called(id)

	var r0 model.Project
	if rf, ok := ret.Get(0).(func(string) model.Project); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(model.Project)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserProjects provides a mock function with given fields: userID
func (_m *Store) GetUserProjects(userID string) ([]model.Project, error) {
	ret := _m.Called(userID)

	var r0 []model.Project
	if rf, ok := ret.Get(0).(func(string) []model.Project); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Project)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProject provides a mock function with given fields: id, np
func (_m *Store) UpdateProject(id string, np model.NewProject) (model.Project, error) {
	ret := _m.Called(id, np)

	var r0 model.Project
	if rf, ok := ret.Get(0).(func(string, model.NewProject) model.Project); ok {
		r0 = rf(id, np)
	} else {
		r0 = ret.Get(0).(model.Project)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, model.NewProject) error); ok {
		r1 = rf(id, np)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
