// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProject struct {
	Name     string `json:"name"`
	Category string `json:"category"`
}

type Project struct {
	ID       string `json:"id"`
	UserID   string `json:"userID"`
	Name     string `json:"name"`
	Category string `json:"category"`
}
