// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProject struct {
	Name string `json:"name"`
	Goal int    `json:"goal"`
}

type Project struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Goal     int    `json:"goal"`
	Achieved int    `json:"achieved"`
}
